### ISSUE TITLE
Bug in motivational sentence generation

### ISSUE THREAD

**Issue by Dgree720** [Dgree720/Cal_tracker#2]
' mag er edde beim einlesen der Zeilen

![Screenshot 2024-09-07 204911](https://github.com/user-attachments/assets/36e7b56b-546a-4045-b6a0-6de93dc07cc6)

**Comment by benJsei123** [comment]
hab beim lesen eine option angegeben, die das vermeiden sollte. Wenn es nochmal vorkommt, kannst du dieses issue #2 nochmal öffnen.

**hab auch direkt auf master gemergt**
